import ProjectDescription

let workspace = Workspace(
    name: "ClientServerSwift-Generated",
    projects: [
        "App/**",
        "Backend/**"
    ],
    generationOptions:
            .options(
                enableAutomaticXcodeSchemes: false,
                autogeneratedWorkspaceSchemes: .disabled
            )
)
